server:
  port: 9001
spring:
  application:
    name: nacos-provider
  cloud:
    discovery:
      server-addr: http://192.168.137.152:81
#      server-addr: localhost:8848

management:
  endpoint:
    web:
      exposure:
        include: '*'