server:
  port: 8006

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置Sentinel地址，就是我们的WEB界面
        dashboard: localhost:8080
        #Sentinel配置默认8719端口，被占用端口会自动从+1，直到找到未被占用的端口
        port: 8719
        # 配置为false
      web-context-unify: false

management:
  endpoints:
    web:
      exposure:
        include: '*'