server:
  port: 8009
spring:
  application:
    name: nacos-consumer-openFeign
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719


logging:
  level:
    # openfeign日志以什么级别监控哪个接口
    com.muxiaonong.feign.GoodsFeign: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'


# 激活Sentinel对OpenFeign的支持
feign:
  sentinel:
    enabled: true

